# https://quarto.org/docs/projects/quarto-projects.html
project:
  type: website
  output-dir: ../_site

website:
  title: CaMKII model
  repo-url: https://github.com/ntumitolab/camkii-cardiomyocyte-model
  site-url: https://ntumitolab.github.io/camkii-cardiomyocyte-model/
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    style: docked
    search: true
    contents: auto
    tools:
      - icon: github
        href: https://github.com/ntumitolab/camkii-cardiomyocyte-model

# bibliography: references.bib

# https://quarto.org/docs/output-formats/html-basics.html
format:
  html:
    toc: true
    theme:
      light: cosmo
      dark: darkly

# Default options
# notebook-links: true

# Execution
# execute:
#   cache: true
# engines: ['julia']
