# https://quarto.org/docs/projects/quarto-projects.html
project:
  type: website
  output-dir: _site

# https://quarto.org/docs/websites/
website:
  title: NRVM CaMKII
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/ntumitolab/camkii-cardiomyocyte-model/
  site-url: https://ntumitolab.github.io/camkii-cardiomyocyte-model/
  search:
    show-item-context: true
    type: overlay
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/ntumitolab/camkii-cardiomyocyte-model/
  sidebar:
    title: false
    style: floating
    collapse-level: 2
    align: left
    contents:
      - index.qmd
      - "*.ipynb"
      - modeldesc.qmd

# bibliography: references.bib

# https://quarto.org/docs/output-formats/html-basics.html
format:
  html:
    respect-user-color-scheme: true
    toc: true
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 350px
    # keep-md: true
    # css: styles.css
# execute:
#   output: asis
